# Chapter2 넘파이

Numpy : 수치계산 위한 라이브러리, 모듈 
다차원 배열을 효율적으로 구현


In [2]:
import timeit

t1=timeit.timeit('[i**2 for i in A]',setup='A=range(100)')
print(t1)
t2=timeit.timeit('b**2',setup='import numpy as np; b=np.arange(100)')
print(t2)

4.85204030002933
0.48355280002579093


In [6]:
import numpy as np
A = np.array([1,2,3],dtype=np.int64)
print(A)

[1 2 3]


In [7]:
len(A)

3

In [8]:
type(A[0])

numpy.int64

In [10]:
def sum_of(n,power=2):
    return sum([i**power for i in range(1,n+1)]) 

print(3**2)
print(sum_of(3,3))

9
36


In [15]:
import numpy as np
arr =np.arange(1,6)
arr2 = np.array([5,4,3,2,1])
print(arr)
print(arr2)
result = arr+arr2
print(result)

[1 2 3 4 5]
[5 4 3 2 1]
[6 6 6 6 6]


In [20]:
arr =np.linspace(0, 100, 20)
print(arr)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


2.3.3 shape 변환함수

-배열의  shape를 변경할 수 있는 함수

-reshape 메소드 배열의 데이터를 공유하는 shape가 다른 view를 생성

In [28]:
#0~15의 원소로이루어진 배열 A생성

A = np.arange(16)
print(A)
C = A[1:-1]
print(C)
B = A.reshape(4,4)
print(B)

B.base is A

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


True

In [29]:
# 파일을 열고 각 줄 앞에 번호를 붙여 새 파일에 저장하는 함수
def add_line_numbers(input_file_path, output_file_path):
    try:
        # 입력 파일을 읽기 모드로 열기
        with open(input_file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        # 출력 파일을 쓰기 모드로 열기
        with open(output_file_path, 'w', encoding='utf-8') as file:
            # 각 줄에 대해 반복
            for i, line in enumerate(lines, start=1):
                # 줄 번호와 함께 해당 줄을 새 파일에 쓰기
                file.write(f"{i}: {line}")
                
        print("파일 처리가 완료되었습니다.")
        
    except Exception as e:
        print(f"오류가 발생했습니다: {e}")

# 사용 예제
input_file_path = 'example.txt'  # 이 부분을 읽고자 하는 파일 경로로 변경하세요.
output_file_path = 'numbered_example.txt'  # 이 부분을 원하는 출력 파일 경로로 변경하세요.

add_line_numbers(input_file_path, output_file_path)

파일 처리가 완료되었습니다.


2.2.4 배열 결합 함수

-배열 결합시 사용하는 함수 뷰가 아닌 새로운 배열을 리턴한다.

-기존배열에 영향을 주지않는다.

In [33]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])
C = np.vstack([A,B])
D = np.hstack([A,B])

print(A)
print(B)
print(C)
print(D)

[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[[1 2]
 [3 4]
 [1 0]
 [0 1]]
[[1 2 1 0]
 [3 4 0 1]]


In [34]:
#column_stack

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

E = np.column_stack([a,b,c])
print(E)
print(a)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3]


In [35]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])

print(np.concatenate((A,B),axis=0))
print(np.concatenate((A,B),axis=1))

[[1 2]
 [3 4]
 [1 0]
 [0 1]]
[[1 2 1 0]
 [3 4 0 1]]


In [1]:
#hsplit 행 방향 분할 -> 세로 방향
import numpy as np
A = np.arange(9).reshape(3,3)

a =np.hsplit(A,3)
print(a)
B= np.arange(18).reshape(3,6)
#3행 6열 생성
print(B)

b=np.hsplit(B,(1,3,5))
#2열과 4열로 끊겠다

print(b)

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0],
       [ 6],
       [12]]), array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5],
       [11],
       [17]])]


In [43]:
#Vsplit
A = np.arange(9).reshape(3,3)
print(A)

a = np.vsplit(A,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [48]:
B= np.arange(24).reshape(6,4)
print(B)
b= np.vsplit(B,(1,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [60]:
A = np.arange(35)
print(A)
B = A.reshape(7,5)
print(B)
b=np.vsplit(B,(1,4))
print(b)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
[array([[0, 1, 2, 3, 4]]), array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])]


In [76]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack([a,b])
d = np.hstack([a,b])

print(c)
print(d)
print(np.concatenate((a,b),axis=0))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]


In [73]:
import numpy as np
a = np.array([[2,3],[5,7]])
b = np.array([[1,1],[1,1]])
c = np.hstack((a,b))
print(c)

[[2 3 1 1]
 [5 7 1 1]]


2.3.1 인덱싱

파이썬 처럼 인덱싱이 가능

In [83]:
import numpy as np

A = np.arange(0,15,2)
print(A)

print(A.shape)

# 인덱스가 음수이면 배열의 마지막부터
print(A[-1])

a = np.arange(12).reshape(3,4)
print(a)
print(a.ndim)

[ 0  2  4  6  8 10 12 14]
(8,)
14
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [87]:
A = np.arange(9).reshape(3,3)
print(A)

for rows in A:
    print(rows)

for column in A.T:
    print(column)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]
[0 3 6]
[1 4 7]
[2 5 8]


In [89]:
#배열 원소 개별 출력 flat

A = np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


2.3.2 슬라이싱

- 배열의 일부 지정 원소값 읽어오거나 변경 

In [97]:
import numpy as np
A = np.arange(0,15,2)
print(A)
B = np.arange(15)
print(B[:-2])

[ 0  2  4  6  8 10 12 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [103]:
A = np.arange(12).reshape(3,4)

print(A)
A.shape
print(A[0]) 
#행은 이런식으로 가능

#열은?
print(A[:,0])

print(A[...,0])
print(A[:,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[0 4 8]
[0 4 8]
[1 5 9]


2.4 얕은 복사와 깊은 복사
-넘파이 배열을 다룰때 3가지경우가 있다.
-대입
넘파이 배열을 가리키는 변수를 다른변수에 대입하면 2개의 변수가 하나의 넘파이 배열을 가리킨다.

In [4]:
A = np.arange(0,15,2)
print(A)
A[:4]

[ 0  2  4  6  8 10 12 14]


array([0, 2, 4, 6])